name: Azure Publish
on: workflow_dispatch

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/ServiceStack/_packaging/pre_release/nuget/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: azure-pack.yml
          # workflow_conclusion: success
          name: ServiceStack Packages
          commit: ${{ github.sha }}
          path: ./build/staging
          
      - name: Check output
        working-directory: ./build
        run: |
          cd staging
          export number_of_packages=$(ls -1 | wc -l)
          echo "number_of_packages=${number_of_packages}" >> $GITHUB_ENV
          dotnet nuget add source ${{ env.AZURE_ARTIFACTS_FEED_URL }} -n pre-release -u pre-release -p ${{ secrets.AZURE_DEVOPS_TOKEN }} --store-password-in-clear-text

      - name: Clear packages
        working-directory: ./build/staging
        shell: bash
        run: |
          ls -1 | grep .nupkg$ | sed -e "s/^\(.*\)\.\([0-9]\.[0-9]\.[0-9]\).*$/\1 \2/" | while read line
          do 
            dotnet nuget delete ${line} --source ${{ env.AZURE_ARTIFACTS_FEED_URL }} --api-key ${{ secrets.AZURE_DEVOPS_TOKEN }} --non-interactive
          done

      - name: Push to GitHub
        working-directory: ./build/staging
        run: |
          # Check if more than 73 packages 
          if [[ ${number_of_packages} -gt 73 ]]; then
            echo "Publishing to Azure Artifacts"
            dotnet nuget push '*.nupkg' --source ${{ env.AZURE_ARTIFACTS_FEED_URL }} --api-key ${{ secrets.AZURE_DEVOPS_TOKEN }} --skip-duplicate
          else
            echo 'Less files than expected, skipping push'
            exit 1
          fi
