name: Build Blazor

on:
  push:
    paths:
      - 'ServiceStack.Blazor/**'
      - '.github/workflows/build-blazor.yml'

jobs:
  build-blazor:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build
        working-directory: ServiceStack.Blazor/build
        run: dotnet build ./build.proj

      - uses: actions/upload-artifact@v2
        with:
          name: ServiceStack.Blazor
          retention-days: 1
          path: ./ServiceStack.Blazor/NuGet/*.nupkg
          