name: Build Redis

on:
  push:
    paths:
      - 'ServiceStack.Redis/**'
      - '.github/workflows/build-redis.yml'

jobs:
  build-redis:
    uses: ServiceStack/ServiceStack/.github/workflows/reuse-build-redis.yml@main
    secrets:
      SERVICESTACK_LICENSE: ${{ secrets.SERVICESTACK_LICENSE }}