name: Build CefGlue

on:
  push:
    paths:
      - 'ServiceStack.CefGlue/**'
      - '.github/workflows/build-cefglue.yml'

jobs:
  build-cefglue:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build
        working-directory: ServiceStack.CefGlue/build
        run: dotnet build ./build.proj
          