name: Build ServiceStack

on: 
  push:
    paths:
      - 'ServiceStack/**'
      - 'ServiceStack.OrmLite/**'
      - 'ServiceStack.Redis/**'
      - 'ServiceStack.Text/**'
      - '.github/workflows/build-servicestack.yml'

jobs:
  build-servicestack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true
          
      - name: Build
        run: dotnet build --framework net6.0 ./ServiceStack/src/ServiceStack/ServiceStack.csproj
        
      - name: Test Common
        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.Common.Tests/ServiceStack.Common.Tests.csproj  --logger 'trx;LogFileName=results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Common Tests
          only-summary: 'true'
          path: ./ServiceStack/tests/ServiceStack.Common.Tests/TestResults/results.trx
          reporter: dotnet-trx

      - name: Test ServiceHosts
        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.ServiceHost.Tests/ServiceStack.ServiceHost.Tests.csproj --logger 'trx;LogFileName=results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: ServiceHost Tests
          only-summary: 'true'
          path: ./ServiceStack/tests/ServiceStack.ServiceHost.Tests/TestResults/results.trx
          reporter: dotnet-trx

      - name: Test ServiceModels
        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.ServiceModel.Tests/ServiceStack.ServiceModel.Tests.csproj --logger 'trx;LogFileName=results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: ServiceModels Tests
          only-summary: 'true'
          path: ./ServiceStack/tests/ServiceStack.ServiceModels.Tests/TestResults/results.trx
          reporter: dotnet-trx

      - name: Test WebHost Endpoints
        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/ServiceStack.WebHost.Endpoints.Tests.csproj --logger 'trx;LogFileName=results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: WebHost.Endpoints Tests
          only-summary: 'true'
          path: ./ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/TestResults/results.trx
          reporter: dotnet-trx

      - name: Test OpenApi
        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.OpenApi.Tests/ServiceStack.OpenApi.Tests.csproj --logger 'trx;LogFileName=results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: OpenApi Tests
          path: ./ServiceStack/tests/ServiceStack.OpenApi.Tests/TestResults/results.trx
          reporter: dotnet-trx
        
    