name: Build OrmLite

on:
  push:
    paths:
      - 'ServiceStack.OrmLite/**'
      - '.github/workflows/build-ormlite.yml'

jobs:
  runs-on: ubuntu-20.04
  build-ormlite:
    uses: ServiceStack/ServiceStack/.github/workflows/reuse-build-ormlite.yml@main
    secrets:
      SERVICESTACK_LICENSE: ${{ secrets.SERVICESTACK_LICENSE }}