name: Build Core

on:
  push:
    paths:
      - 'ServiceStack.Core/**'
      - '.github/workflows/build-core.yml'

jobs:
  build-servicestack-core:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true
          
      - name: Build
        working-directory: ServiceStack.Core/build
        run: |
          # chmod +x ./ServiceStack.Core/build/build.sh
          # ./ServiceStack.Core/build/build.sh
          # Using straight dotnet build for now, deal with correct piping of output to GH actions later from script.
          dotnet build ./build.proj /property:Configuration=Release /property:MinorVersion=0 /property:PatchVersion=3    
          
      - uses: actions/upload-artifact@v2
        with:
          name: ServiceStack.Core
          retention-days: 1
          path: ./ServiceStack.Core/NuGet/*.nupkg
    