name: Build ServiceStack.OrmLite

on: [push]
#  push:
#    paths:
#      - 'ServiceStack.OrmLite/**'
#      - 'ServiceStack.Text/**'

jobs:
  build-ormlite:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 48301:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Test!tesT
          MSSQL_PID: Developer
        ports:
          - 48501:1433
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: root
        ports:
          - 48201:3306
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true
          
      - name: Build
        working-directory: ServiceStack.OrmLite/build
        run: dotnet build ./build.proj
        
      - name: Env setup
        run: |
          echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV
        
      - name: Tests Setup
        working-directory: ServiceStack.OrmLite/tests
        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.Tests.Setup/ServiceStack.OrmLite.Tests.Setup.csproj        

      - name: Test Sqlite
        working-directory: ServiceStack.OrmLite/tests
        env:
          ORMLITE_DIALECT: Sqlite
        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj --logger 'trx;LogFileName=test-results.trx'

      - name: Test Report
        working-directory: ServiceStack.OrmLite/tests
        uses: dorny/test-reporter@v1
        if: success() || failure()                                                    # run this step even if previous step failed
        with:
          name: OrmLite Tests                                                         # Name of the check run which will be created
          path: ./ServiceStack.OrmLite.SqliteTests/TestResults/test-results.trx       # Path to test results
          reporter: dotnet-trx                                                        # Format of test results