name: Build ServiceStack

on:
  push:
    paths:
      - 'ServiceStack/**'
      - '.github/workflows/build-servicestack.yml'

jobs:
  runs-on: ubuntu-20.04
  build-servicestack:
    uses: ServiceStack/ServiceStack/.github/workflows/reuse-build-servicestack.yml@main
      secrets:
        SERVICESTACK_LICENSE: ${{ secrets.SERVICESTACK_LICENSE }}
    