name: MyGet Publish

on: #workflow_dispatch
  push:
    paths:
      - '.github/workflows/myget-push.yml'

jobs:
  myget-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-myget.yml
          workflow_conclusion: success
          commit: bd31d2c2cf1d8f7a6b26a8771cf224d819c1ad9c
          path: ./build/staging
          
      - name: Push to MyGet
        working-directory: ./build/staging
        run: |
          # Check if more than 74 packages 
          if [[ ${number_of_packages} -gt 74 ]]; then
            echo "Pushing to MyGet"
            dotnet nuget push '*.nupkg' -s '${{ secrets.MYGET_FEEDURL }}' -k '${{ secrets.MYGET_APIKEY }}'
          else
            echo 'Less files than expected, skipping push'
            exit 1
          fi
          
          