name: Pack MyGet

on: #workflow_dispatch
  push:
    paths:
      - '.github/workflows/pack-myget.yml'

jobs:
  myget-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build All
        working-directory: ./build
        run: |
          chmod +x ./build-all.sh
          chmod +x ../ServiceStack/build/build.sh
          chmod +x ../ServiceStack.Aws/build/build.sh
          chmod +x ../ServiceStack.Azure/build/build.sh
          chmod +x ../ServiceStack.Blazor/build/build.sh
          chmod +x ../ServiceStack.CefGlue/build/build.sh
          chmod +x ../ServiceStack.Logging/build/build.sh
          chmod +x ../ServiceStack.OrmLite/build/build.sh
          chmod +x ../ServiceStack.Redis/build/build.sh
          chmod +x ../ServiceStack.Stripe/build/build.sh
          chmod +x ../ServiceStack.Text/build/build.sh
          chmod +x ../ServiceStack.Core/build/build.sh
          ./build-all.sh

      - name: Stage output
        working-directory: ./build
        run: |
          chmod +x ./stage-output.sh
          ./stage-output.sh
          cd staging
          export number_of_packages=$(ls -1 | wc -l)
          echo "number_of_packages=${number_of_packages}" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: ServiceStack Packages
          retention-days: 1
          path: ./build/staging/*.nupkg