name: Z_Reuse Build OrmLite

on:
  workflow_call:
    secrets:
      SERVICESTACK_LICENSE:
        required: true

jobs:
  build-ormlite-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build
        working-directory: ServiceStack.OrmLite/build
        run: dotnet build ./build.proj

      - name: Env setup
        run: |
          echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV

      - name: Tests Setup
        working-directory: ServiceStack.OrmLite/tests
        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.Tests.Setup/ServiceStack.OrmLite.Tests.Setup.csproj

      - name: Test Sqlite
        working-directory: ServiceStack.OrmLite/tests
        env:
          ORMLITE_DIALECT: Sqlite
        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj --logger 'trx;LogFileName=test-results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: OrmLite Tests
          only-summary: 'true'
          path: ./ServiceStack.OrmLite/tests/ServiceStack.OrmLite.SqliteTests/TestResults/test-results.trx
          reporter: dotnet-trx
          